# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
target 'StrapFlatApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StrapFlatApp

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'
  

  target 'StrapFlatApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StrapFlatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'StrapFlatApp-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for StrapFlatApp-tvOS

#   target 'StrapFlatApp-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
